name: Build and upload artifact
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build application
        run: yarn build
      - name: Get application node-version
        id: package
        run: echo "::set-output name=version::$(cat package.json | jq -r '.version')"
      - name: Install web-ext
        run: yarn web-ext
      - name: Build with web-ext
        run: yarn web-ext build
      - uses: actions/upload-artifact@v2
        with:
          name: backlog_notification_extension-${{ steps.package.outputs.version }}
          path: web-ext-artifacts/*.zip
          retention-days: 2
